PROJECT_ID        = "kolban-dataplex-demo-10-06-02"
LOCATION          = "us-central1"
LAKE              = "my-business-4"
ZONE              = "operations"
CUSTOMERS_DATASET = "customers_ds"
SALES_DATASET     = "sales_ds"
